// <auto-generated />
using Entity_HomeWorks_OneToOne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Relationships.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.AccountSettings.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.AccountSettings.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.CarRegistration.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.CarRegistration.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.PersonPassport.Passport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Passport");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.PersonPassport.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.StudentCard.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardNumber")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Card");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.StudentCard.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.UserProfile.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.UserProfile.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.AccountSettings.Settings", b =>
                {
                    b.HasOne("Entity_HomeWorks_OneToOne.Models.OneToOne.AccountSettings.Account", "Account")
                        .WithOne("Settings")
                        .HasForeignKey("Entity_HomeWorks_OneToOne.Models.OneToOne.AccountSettings.Settings", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.CarRegistration.Registration", b =>
                {
                    b.HasOne("Entity_HomeWorks_OneToOne.Models.OneToOne.CarRegistration.Car", "Car")
                        .WithOne("Registration")
                        .HasForeignKey("Entity_HomeWorks_OneToOne.Models.OneToOne.CarRegistration.Registration", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.PersonPassport.Passport", b =>
                {
                    b.HasOne("Entity_HomeWorks_OneToOne.Models.OneToOne.PersonPassport.Person", "Person")
                        .WithOne("Passport")
                        .HasForeignKey("Entity_HomeWorks_OneToOne.Models.OneToOne.PersonPassport.Passport", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.StudentCard.Card", b =>
                {
                    b.HasOne("Entity_HomeWorks_OneToOne.Models.OneToOne.StudentCard.Student", "Student")
                        .WithOne("Card")
                        .HasForeignKey("Entity_HomeWorks_OneToOne.Models.OneToOne.StudentCard.Card", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.UserProfile.UserProfile", b =>
                {
                    b.HasOne("Entity_HomeWorks_OneToOne.Models.OneToOne.UserProfile.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Entity_HomeWorks_OneToOne.Models.OneToOne.UserProfile.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.AccountSettings.Account", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.CarRegistration.Car", b =>
                {
                    b.Navigation("Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.PersonPassport.Person", b =>
                {
                    b.Navigation("Passport")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.StudentCard.Student", b =>
                {
                    b.Navigation("Card")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity_HomeWorks_OneToOne.Models.OneToOne.UserProfile.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
